version: '3.8'

services:
  dota-discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./audio:/app/audio
      - ./tts_cache:/app/tts_cache
    restart: always
