version: '3.8'

services:
  dota-discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - WEBHOOK_ID=${WEBHOOK_ID}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./audio:/app/audio
      - ./tts_cache:/app/tts_cache
    ports:
      - "5000:5000"  # Expose web dashboard port
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s